import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Brain, Target, BarChart, Users, CheckCircle, ArrowRight, Play, BookOpen, Trophy, Clock, Sparkles, Globe, Shield, Award } from "lucide-react";

const LandingPage = () => {
  const { user } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (user) {
      navigate('/dashboard', { replace: true });
    }
  }, [user, navigate]);

  const handleDemoMode = () => {
    // Set a demo flag in localStorage to enable demo mode
    localStorage.setItem('studyforge-demo-mode', 'true');
    navigate('/dashboard');
  };

  const features = [
    {
      icon: <Brain className="h-8 w-8 text-primary" />,
      title: "AI-Powered Learning",
      description: "Personalized study roadmaps generated by advanced AI algorithms that adapt to your learning style and pace.",
      color: "from-blue-500 to-cyan-500"
    },
    {
      icon: <Target className="h-8 w-8 text-success" />,
      title: "Smart Goal Tracking",
      description: "Set and achieve your learning goals with intelligent progress tracking and milestone celebrations.",
      color: "from-green-500 to-emerald-500"
    },
    {
      icon: <Users className="h-8 w-8 text-secondary" />,
      title: "Study Groups",
      description: "Connect with peers, join study rooms, and collaborate on challenging topics together.",
      color: "from-purple-500 to-pink-500"
    },
    {
      icon: <BarChart className="h-8 w-8 text-warning" />,
      title: "Progress Analytics",
      description: "Detailed insights into your learning patterns, strengths, and areas that need improvement.",
      color: "from-orange-500 to-yellow-500"
    },
    {
      icon: <Clock className="h-8 w-8 text-primary" />,
      title: "Flexible Scheduling",
      description: "Study when it suits you best with adaptive scheduling that fits your lifestyle.",
      color: "from-indigo-500 to-blue-500"
    },
    {
      icon: <Trophy className="h-8 w-8 text-success" />,
      title: "Achievement System",
      description: "Stay motivated with badges, streaks, and rewards for consistent learning progress.",
      color: "from-yellow-500 to-orange-500"
    }
  ];

  const stats = [
    { number: "10K+", label: "Active Learners", icon: <Users className="h-5 w-5" /> },
    { number: "500K+", label: "Study Sessions", icon: <BookOpen className="h-5 w-5" /> },
    { number: "95%", label: "Success Rate", icon: <Trophy className="h-5 w-5" /> },
    { number: "50+", label: "Subjects", icon: <Globe className="h-5 w-5" /> }
  ];

  return (
    <div className="flex flex-col min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-card/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="p-2 bg-primary/10 rounded-lg">
                <img src="/favicon.svg" alt="StudyForge Logo" className="h-8 w-8" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-foreground">StudyForge</h1>
                <p className="text-sm text-muted-foreground">AI-Powered Learning</p>
              </div>
            </div>
            <nav className="hidden md:flex items-center space-x-6">
              <a href="#features" className="text-sm font-medium text-muted-foreground hover:text-primary transition-colors">Features</a>
              <a href="#stats" className="text-sm font-medium text-muted-foreground hover:text-primary transition-colors">Stats</a>
              <a href="#pricing" className="text-sm font-medium text-muted-foreground hover:text-primary transition-colors">Pricing</a>
              <Button variant="ghost" asChild>
                <a href="/auth">Sign In</a>
              </Button>
              <Button asChild>
                <a href="/auth">Get Started</a>
              </Button>
            </nav>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <main className="flex-1">
        <section className="relative overflow-hidden">
          {/* Background Pattern */}
          <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-secondary/5 to-accent/5"></div>
          <div className="absolute inset-0 bg-grid-pattern opacity-5"></div>

          <div className="container mx-auto px-6 py-24 relative">
            <div className="max-w-4xl mx-auto text-center">
              {/* Badge */}
              <div className="inline-flex items-center gap-2 bg-primary/10 text-primary px-4 py-2 rounded-full text-sm font-medium mb-8">
                <Sparkles className="h-4 w-4" />
                Now with AI-Powered Study Plans
              </div>

              {/* Main Headline */}
              <h1 className="text-5xl md:text-7xl font-bold leading-tight mb-6">
                Master Any Subject with
                <span className="bg-gradient-to-r from-primary via-secondary to-accent bg-clip-text text-transparent"> AI Intelligence</span>
              </h1>

              <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8 leading-relaxed">
                Transform your learning journey with personalized study roadmaps, adaptive scheduling, and intelligent progress tracking powered by advanced AI.
              </p>

              {/* CTA Buttons */}
              <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
                <Button size="lg" className="bg-gradient-to-r from-primary to-secondary hover:opacity-90 text-white px-8 py-4 text-lg" asChild>
                  <a href="/auth">
                    <Play className="h-5 w-5 mr-2" />
                    Start Learning Free
                  </a>
                </Button>
                <Button size="lg" variant="outline" className="px-8 py-4 text-lg border-2" onClick={handleDemoMode}>
                  <BookOpen className="h-5 w-5 mr-2" />
                  Try Demo Mode
                </Button>
              </div>

              {/* Trust Indicators */}
              <div className="flex flex-wrap items-center justify-center gap-6 text-sm text-muted-foreground">
                <div className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-success" />
                  No credit card required
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-success" />
                  14-day free trial
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-success" />
                  Cancel anytime
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Stats Section */}
        <section id="stats" className="py-16 bg-muted/30">
          <div className="container mx-auto px-6">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
              {stats.map((stat, index) => (
                <div key={index} className="text-center">
                  <div className="flex items-center justify-center mb-2">
                    <div className="p-2 bg-primary/10 rounded-lg">
                      {stat.icon}
                    </div>
                  </div>
                  <div className="text-3xl font-bold text-primary mb-1">{stat.number}</div>
                  <div className="text-sm text-muted-foreground">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="py-24">
          <div className="container mx-auto px-6">
            <div className="text-center mb-16">
              <h2 className="text-4xl font-bold mb-4">Why Choose StudyForge?</h2>
              <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
                Everything you need to excel in your studies, powered by cutting-edge AI technology.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {features.map((feature, index) => (
                <Card key={index} className="border-2 hover:border-primary/20 transition-all duration-300 hover:shadow-lg group">
                  <CardHeader>
                    <div className={`w-16 h-16 rounded-xl bg-gradient-to-br ${feature.color} p-4 mb-4 group-hover:scale-110 transition-transform duration-300`}>
                      {feature.icon}
                    </div>
                    <CardTitle className="text-xl mb-2">{feature.title}</CardTitle>
                    <CardDescription className="text-base leading-relaxed">
                      {feature.description}
                    </CardDescription>
                  </CardHeader>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-24 bg-gradient-to-r from-primary/10 via-secondary/10 to-accent/10">
          <div className="container mx-auto px-6 text-center">
            <h2 className="text-4xl font-bold mb-4">Ready to Transform Your Learning?</h2>
            <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
              Join thousands of students who are already achieving their goals with StudyForge.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button size="lg" className="bg-gradient-to-r from-primary to-secondary hover:opacity-90 text-white px-8 py-4 text-lg" asChild>
                <a href="/auth">
                  <ArrowRight className="h-5 w-5 mr-2" />
                  Start Your Journey
                </a>
              </Button>
              <Button size="lg" variant="outline" className="px-8 py-4 text-lg" onClick={handleDemoMode}>
                <Play className="h-5 w-5 mr-2" />
                Watch Demo
              </Button>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t bg-card py-12">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div className="col-span-1 md:col-span-2">
              <div className="flex items-center space-x-3 mb-4">
                <div className="p-2 bg-primary/10 rounded-lg">
                  <img src="/favicon.svg" alt="StudyForge Logo" className="h-6 w-6" />
                </div>
                <span className="text-xl font-bold">StudyForge</span>
              </div>
              <p className="text-muted-foreground mb-4 max-w-md">
                Empowering learners worldwide with AI-driven study solutions. Transform your learning experience today.
              </p>
              <div className="flex space-x-4">
                <Badge variant="secondary" className="flex items-center gap-1">
                  <Shield className="h-3 w-3" />
                  Secure
                </Badge>
                <Badge variant="secondary" className="flex items-center gap-1">
                  <Globe className="h-3 w-3" />
                  Global
                </Badge>
                <Badge variant="secondary" className="flex items-center gap-1">
                  <Award className="h-3 w-3" />
                  Trusted
                </Badge>
              </div>
            </div>

            <div>
              <h3 className="font-semibold mb-4">Product</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><a href="#features" className="hover:text-primary transition-colors">Features</a></li>
                <li><a href="/auth" className="hover:text-primary transition-colors">Pricing</a></li>
                <li><a href="/auth" className="hover:text-primary transition-colors">Demo</a></li>
                <li><a href="/auth" className="hover:text-primary transition-colors">API</a></li>
              </ul>
            </div>

            <div>
              <h3 className="font-semibold mb-4">Support</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><a href="/auth" className="hover:text-primary transition-colors">Help Center</a></li>
                <li><a href="/auth" className="hover:text-primary transition-colors">Contact Us</a></li>
                <li><a href="/auth" className="hover:text-primary transition-colors">Community</a></li>
                <li><a href="/auth" className="hover:text-primary transition-colors">Status</a></li>
              </ul>
            </div>
          </div>

          <div className="border-t mt-8 pt-8 text-center text-sm text-muted-foreground">
            <p>&copy; 2025 StudyForge. All rights reserved. Made with ❤️ for learners worldwide.</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
